# Generated by Django 5.2 on 2025-05-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_favorite'),
        ('users', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, to='api.book'),
        ),
    ]
