# Generated by Django 5.2 on 2025-05-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
